import os
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
WEBSITE = ROOT / "website"
DOCS_SRC = ROOT / "docs"
DOCS_DEST = WEBSITE / "public" / "typescript"
BRANCH = "ci/update-typescript-docs"
# The docs are served at hegel.dev/typescript. Vercel's `trailingSlash: false`
# strips the trailing slash from the root page, so the browser resolves
# relative hrefs on /typescript against / — which turns `assets/style.css`
# into `/assets/style.css` (404). Inject <base href="/typescript/"> only on
# the root index.html to fix that one page. Subpages served at e.g.
# /typescript/classes/... already have a directory-like URL, so TypeDoc's
# `../assets/...` hrefs resolve correctly without a <base> tag.
BASE_HREF = "/typescript/"


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=WEBSITE)


def inject_base_href(root: Path, href: str) -> None:
    index = root / "index.html"
    tag = f'<base href="{href}">'
    content = index.read_text(encoding="utf-8")
    content = content.replace("<head>", f"<head>\n{tag}", 1)
    index.write_text(content, encoding="utf-8")


def main() -> None:
    version = os.environ["VERSION"]
    app_id = os.environ["HEGEL_RELEASE_APP_ID"]
    app_slug = os.environ["HEGEL_RELEASE_APP_SLUG"]

    if DOCS_DEST.exists():
        shutil.rmtree(DOCS_DEST)
    shutil.copytree(DOCS_SRC, DOCS_DEST)
    inject_base_href(DOCS_DEST, BASE_HREF)

    git("config", "user.name", f"{app_slug}[bot]")
    git("config", "user.email", f"{app_id}+{app_slug}[bot]@users.noreply.github.com")

    git("checkout", "-b", BRANCH)
    git("add", "public/typescript")

    status = subprocess.check_output(
        ["git", "status", "--porcelain"], cwd=WEBSITE, text=True
    )
    if not status.strip():
        print("No doc changes to publish.")
        return

    git("commit", "-m", f"Update hegel-typescript docs to v{version}")
    git("push", "--force", "origin", BRANCH)

    result = subprocess.run(
        ["gh", "pr", "list", "--head", BRANCH, "--state", "open", "--json", "number"],
        capture_output=True,
        text=True,
        cwd=WEBSITE,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    title = f"Update `hegel-typescript` docs to v{version}"
    ci_url = "https://github.com/hegeldev/hegel-typescript/blob/main/.github/workflows/ci.yml"
    body = (
        f"Updates [hegel-typescript](https://github.com/hegeldev/hegel-typescript) docs to "
        f"`v{version}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [this workflow]({ci_url}).*"
    )
    cmd = ["gh", "pr", "edit", BRANCH] if has_open_pr else ["gh", "pr", "create"]
    subprocess.run(cmd + ["--title", title, "--body", body], check=True, cwd=WEBSITE)


if __name__ == "__main__":
    main()
