// Code generated by scripts/update-libhegel.mjs; DO NOT EDIT.
//
// Run `just update-libhegel` to pin the latest libhegel release.

/**
 * The pinned libhegel version this client targets.
 */
export const LIBHEGEL_VERSION = "0.42.4";
