// Code generated by scripts/update-libhegel.mjs; DO NOT EDIT.
//
// Run `just update-libhegel` to pin the latest hegel-rust release.

/**
 * The pinned libhegel version this client targets.
 */
export const LIBHEGEL_VERSION = "0.33.0";
