// Code generated by scripts/update-libhegel.mjs; DO NOT EDIT.
//
// Run `just update-libhegel` after auditing the matching published Wasm pin.

/**
 * The pinned libhegel version this client targets.
 */
export const LIBHEGEL_VERSION = "0.38.1";
