name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: format
        run: |
          npm run format
          git diff --exit-code

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base
        with:
          ssh-key: ${{ secrets.HEGEL_DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install hegel
        run: |
          pip install git+ssh://git@github.com/antithesishq/hegel.git
      - run: npm ci
      - run: npm run test

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run docs

  conformance:
    name: conformance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base
        with:
          ssh-key: ${{ secrets.HEGEL_DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install hegel
        run: |
          pip install git+ssh://git@github.com/antithesishq/hegel.git
          pip install pytest
      - run: npm ci
      - name: Run conformance tests
        working-directory: tests/conformance
        run: pytest test_conformance.py --durations=20 --durations-min=1.0
